[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class scratchpad"
size = "800px 600px"
lazy = true

[scratchpads.music]
animation = "fromTop"
command = "spotify"
class = "Spotify"
match_by = "class"
unfocus = "hide"
size = "800px 600px"
lazy = true
