[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromBottom"
command = "kitty --class scratchpad"
size = "800px 600px"
lazy = true

[scratchpads.music]
animation = "fromBottom"
command = "spotify --enable-features=UseOzonePlatform --ozone-platform=wayland --class scratchpad"
unfocus = "hide"
size = "800px 600px"
lazy = true
